version: '3.8'

services:
  jupyterlab:
    image: python:3.9
    container_name: jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    working_dir: /workspace
    env_file: .env
    environment:
      - POETRY_HOME=/poetry
      - POETRY_VIRTUALENVS_CREATE=false
    entrypoint: ["./docker-entrypoint.sh"]

volumes:
  jupyterlab_data: