version: '3.8'

services:
  jupyterlab:
    build: .
    container_name: jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/workspace/notebooks
    env_file: .env
    environment:
      - POETRY_HOME=/poetry
      - POETRY_VIRTUALENVS_CREATE=false

volumes:
  jupyterlab_data: